sudo: false
language: node_js
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  flowdock: e7454f5285e7b9ab67009802d5560490
node_js:
- '0.10'
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: g9VJjWiqKhOoGy3L9W79QeTC7cK6kO6cDYLH7OLNsR2HEB7JtPToAQdM/OOd2phSBIhNgisFtps9beFhhry9Rjpv4wO8S5abLrmlgjqc0+aSCflvJNuuWCANepR4dfOWhwu1X5Z/E+a3EJmgJZ4ADpVUk05oMJQ5UNI+M+Xl2cw=
  on:
    tags: true
    all_branches: true
