language: node_js
node_js:
- '0.10'
before_install:
  - npm install npm -g
before_deploy:
  - npm install ws browserify coffeeify
  - mkdir -p deploy/meshblu-lifx/latest
  - mkdir -p deploy/meshblu-lifx/$TRAVIS_TAG
  - node_modules/.bin/browserify -t coffeeify -s Connector connector.js > deploy/meshblu-lifx/latest/meshblu-lifx.js
  - gzip deploy/meshblu-lifx/latest/meshblu-lifx.js
  - mv deploy/meshblu-lifx/latest/meshblu-lifx.js.gz deploy/meshblu-lifx/latest/meshblu-lifx.js
  - cp deploy/meshblu-lifx/latest/meshblu-lifx.js deploy/meshblu-lifx/$TRAVIS_TAG/meshblu-lifx.js
deploy:
  - provider: s3
    region: us-west-2
    skip_cleanup: true
    detect_encoding: true
    access_key_id: AKIAJH2D5IPIRHYJT5IA
    secret_access_key:
      secure: "RUrqaCR8Qh3kYxHBsTlP8YcgwQco38xgH5N+981WUBhKwi4QxXGTGTQJ2gVvVtqAp1fm929EpraIR7f8U+m9ujNoCJTfiH8j9+DGeXNtJdBHXynZHolCCosmQybUoCW1RwpTZPAJK2zlZTzW1gqO7V7BxT4/SLdVtYimAFbtkec="
    bucket: octoblu-cdn
    local-dir: deploy
    upload-dir: js
    on:
      tags: true
      all_branches: true
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: serveradmin@octoblu.com
    api_key:
      secure: "RRVzEy29jULc6HHOT6ILhduEr9UUrY0ohY4A/h0jSReWSXH9XAQwS5epGkVEE7UZlpx0YpRHeyrOZuiuo1xe+Y2Me9Gmqre0w98CHP+o/Eck5M7WCHA58hTpLarCCwlZ++0x+i7p0rbhtto7F4JEGKf0XrlVuOyJ5H/TkSsWhMY="
    on:
      tags: true
      all_branches: true
